image: node:16

pages:
  cache:
    key:
      files:
        - yarn.lock
    paths:
      - node_modules
  before_script:
    - npm config set "@fortawesome:registry" https://npm.fontawesome.com/
    - npm config set "//npm.fontawesome.com/:_authToken" ${FORTAWESOME_TOKEN}
  script:
    - yarn install --frozen-lockfile
    - yarn build
    - rm -rf public
    - mv out public
  artifacts:
    paths:
      - public