nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.5.0.cjs

npmRegistries:
  //npm.fontawesome.com:
    npmAlwaysAuth: true
    npmAuthToken: "${FONTAWESOME_NPM_TOKEN}"

npmScopes:
  fortawesome:
    npmRegistryServer: https://npm.fontawesome.com/