nodeLinker: node-modules

npmRegistries:
  //npm.fontawesome.com:
    npmAlwaysAuth: true
    npmAuthToken: "${FONTAWESOME_NPM_TOKEN}"

npmScopes:
  fortawesome:
    npmRegistryServer: "https://npm.fontawesome.com/"

yarnPath: .yarn/releases/yarn-4.0.2.cjs
